from pathlib import Path
import re
p = Path('frontend/index.html')
text = p.read_text(encoding='utf-8')
# Find all <script>...</script> blocks (non-greedy)
pattern = re.compile(r'<script(?:\s[^>]*)?>([\s\S]*?)</script>', re.IGNORECASE)
matches = pattern.findall(text)
if not matches:
    raise SystemExit('No <script> blocks found')
# Choose the largest script block
script = max(matches, key=len)
out = Path('frontend_check.js')
out.write_text('/* Extracted from frontend/index.html - generated by tools/extract_frontend_script.py */\n' + script, encoding='utf-8')
print('Wrote frontend_check.js (' + str(len(script)) + ' bytes)')
